# Generated by Django 4.2.11 on 2024-11-25 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                ("slug", models.SlugField(unique=True)),
                ("body", models.TextField(blank=True, verbose_name="Post")),
                ("done", models.BooleanField(default=False, verbose_name="Done")),
                (
                    "priority",
                    models.TextField(
                        choices=[
                            ("High", "High Priority"),
                            ("Middle", "Middle Priority"),
                            ("Low", "Low Priority"),
                        ],
                        verbose_name="Priority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
